FROM ghcr.io/nginxinc/nginx-unprivileged:stable-alpine-slim

EXPOSE 8080

ENV BASE_URL=""
ENV SEERR_URL=""
ENV HIDE_PASSWORD_LOGIN=""

USER root
COPY build/web /usr/share/nginx/html
RUN chown -R nginx:nginx /usr/share/nginx/html

USER nginx
RUN mkdir -p /usr/share/nginx/html/assets/config && \
    echo '{"baseUrl": "${BASE_URL}", "seerrUrl": "${SEERR_URL}", "hidePasswordLogin": __HIDE_PW__}' > /usr/share/nginx/html/assets/config/config.json

USER root
CMD /bin/sh -c '\
  HIDE_PW_VAL=$([ "$HIDE_PASSWORD_LOGIN" = "true" ] && echo true || echo null) && \
  sed -i "s|__HIDE_PW__|${HIDE_PW_VAL}|g" /usr/share/nginx/html/assets/config/config.json && \
  sed -i "s|\${BASE_URL}|${BASE_URL}|g" /usr/share/nginx/html/assets/config/config.json && \
  sed -i "s|\${SEERR_URL}|${SEERR_URL}|g" /usr/share/nginx/html/assets/config/config.json && \
  nginx -g "daemon off;"'