FROM ghcr.io/nginxinc/nginx-unprivileged:stable-alpine-slim

EXPOSE 8080

ENV BASE_URL=""
ENV SEERR_URL=""
ENV HIDE_PASSWORD_LOGIN=""
ENV SEERR_CUSTOM_HEADERS=""
ENV PORT=8080

USER root
RUN apk add --no-cache jq
COPY build/web /usr/share/nginx/html
COPY docker/docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh && \
    chown -R nginx:nginx /usr/share/nginx/html

CMD ["/docker-entrypoint.sh"]
