name: Build Fladder Windows (Manual)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '要编译的分支'
        required: false
        default: 'custom-dev'
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fetch-info:
    runs-on: ubuntu-latest
    outputs:
      version_name: ${{ steps.fetch.outputs.version_name }}
      flutter_version: ${{ steps.fetch.outputs.flutter_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.inputs.branch || 'custom-dev' }}

      - name: Fetch version info
        id: fetch
        run: |
          VERSION_NAME=$(grep '^version:' pubspec.yaml | cut -d ':' -f2 | cut -d '+' -f1 | tr -d ' ')
          echo "version_name=${VERSION_NAME}" >> "$GITHUB_OUTPUT"
          
          FLUTTER_VERSION=$(jq -r '.flutter' .fvmrc)
          echo "flutter_version=${FLUTTER_VERSION}" >> "$GITHUB_OUTPUT"
          
          echo "Branch: ${{ github.event.inputs.branch || 'custom-dev' }}"
          echo "Version: $VERSION_NAME"
          echo "Flutter: $FLUTTER_VERSION"
        shell: bash

  build-windows:
    runs-on: windows-2022
    needs: [fetch-info]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.inputs.branch || 'custom-dev' }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.19.0
        with:
          channel: "stable"
          flutter-version: ${{needs.fetch-info.outputs.flutter_version}}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows EXE
        run: flutter build windows --build-number=${{ github.run_number }}

      - name: Compile Inno Setup installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: windows/windows_setup.iss
          options: /O+ /DFLADDER_VERSION="${{ needs.fetch-info.outputs.version_name }}"

      - name: Archive Windows portable artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: fladder-windows-portable
          path: build\windows\x64\runner\Release\

      - name: Archive Windows installer artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: fladder-windows-installer
          path: windows\Output\fladder_setup.exe